// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cuwwphjyhnuufbnedlzf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1d3dwaGp5aG51dWZibmVkbHpmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyNjk3NDMsImV4cCI6MjA3Mzg0NTc0M30.xmrP_SVS4M-gJmavXijacydj8WW7cAqa2WciO9mULjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});